CREATE TABLE [dbo].[Schemata] (
    [Id] INT IDENTITY NOT NULL,
    [SchemaInfoId] INT NOT NULL,
	[Type] INT NOT NULL,
	[TypeArrayId] INT NOT NULL,
    [IncludeTypeName] BIT NOT NULL,
    [IntegerSchemaId] INT NULL, 
    [NumberSchemaId] INT NULL, 
    [StringSchemaId] INT NULL, 
    [ArraySchemaId] INT NULL, 
    [EnumSchemaId] INT NULL, 
    [ObjectSchemaId] INT NULL, 
    [AllOfSchemaArrayId] INT NULL,
    [AnyOfSchemaArrayId] INT NULL,
    [OneOfSchemaArrayId] INT  NULL,
    [NotSchemaReferenceId] INT  NULL,
    [MetadataId] INT  NULL,
    CONSTRAINT [PK_Schemata] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Schemata_SchemaInfo] FOREIGN KEY ([SchemaInfoId]) REFERENCES [SchemaInfo]([Id]),
    CONSTRAINT [FK_Schemata_SimpleTypesArray] FOREIGN KEY ([TypeArrayId]) REFERENCES [SimpleTypeArrays]([Id]),
    CONSTRAINT [FK_Schemata_IntegerSchemata] FOREIGN KEY ([IntegerSchemaId]) REFERENCES [IntegerSchemata]([Id]),
    CONSTRAINT [FK_Schemata_NumberSchemata] FOREIGN KEY ([NumberSchemaId]) REFERENCES [NumberSchemata]([Id]),
    CONSTRAINT [FK_Schemata_StringSchemata] FOREIGN KEY ([StringSchemaId]) REFERENCES [StringSchemata]([Id]),
    CONSTRAINT [FK_Schemata_SchemaCollections] FOREIGN KEY ([ArraySchemaId]) REFERENCES [SchemaCollections]([Id]),
    CONSTRAINT [FK_Schemata_EnumSchemata] FOREIGN KEY ([EnumSchemaId]) REFERENCES [EnumSchemata]([Id]),
    CONSTRAINT [FK_Schemata_ObjectSchemata] FOREIGN KEY ([ObjectSchemaId]) REFERENCES [ObjectSchemata]([Id]),
	CONSTRAINT [FK_Schemata_SchemaCollections_AllOf] FOREIGN KEY ([AllOfSchemaArrayId]) REFERENCES [SchemaCollections]([Id]),
    CONSTRAINT [FK_Schemata_SchemaCollections_AnyOf] FOREIGN KEY ([AnyOfSchemaArrayId]) REFERENCES [SchemaCollections]([Id]),
    CONSTRAINT [FK_Schemata_SchemaCollections_OneOf] FOREIGN KEY ([OneOfSchemaArrayId]) REFERENCES [SchemaCollections]([Id]),
    CONSTRAINT [FK_Schemata_SchemaReferences_Not] FOREIGN KEY ([NotSchemaReferenceId]) REFERENCES [SchemaReferences]([Id]),
    CONSTRAINT [FK_Schemata_Metadata] FOREIGN KEY ([MetadataId]) REFERENCES [Metadata]([Id])
);
