CREATE TABLE [dbo].[Values] (
    [Id] INT IDENTITY NOT NULL,
    [SchemaId] INT NULL,
    [PropertySchemaReferenceId] INT NULL,
    [Ordinal] INT NULL,
	[ParentArrayId] INT NULL,
	[ParentObjectId] INT NULL,
    [Name] NVARCHAR(256) NULL,
    [IntegerValue] INT NULL, 
    [NumberValue] FLOAT NULL, 
    [StringValue] NVARCHAR(MAX) NULL, 
    [ArrayValueId] INT NULL, 
    [EnumValue] NVARCHAR(1024) NULL, 
    [ObjectValueId] INT NULL,
	[FunctionValueId] INT NULL,
    [SchemaReferenceValueId] INT NULL,
	[ExecutionContextValueId] INT NULL,
	[ScopeValueId] INT NULL,
	[IdentifierValueId] INT NULL,
    [MetadataId] INT NULL, 
    CONSTRAINT [PK_Values] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [FK_Values_Schemata] FOREIGN KEY ([SchemaId]) REFERENCES [Schemata]([Id]),
    CONSTRAINT [FK_Values_SchemaReferences_PropertySchema] FOREIGN KEY ([PropertySchemaReferenceId]) REFERENCES [SchemaReferences]([Id]),
    CONSTRAINT [FK_Values_Arrays_Parent] FOREIGN KEY ([ParentArrayId]) REFERENCES [Arrays]([Id]),
    CONSTRAINT [FK_Values_Objects_Parent] FOREIGN KEY ([ParentObjectId]) REFERENCES [Objects]([Id]),
    CONSTRAINT [FK_Values_Arrays_Value] FOREIGN KEY ([ArrayValueId]) REFERENCES [Arrays]([Id]),
    CONSTRAINT [FK_Values_Objects_Value] FOREIGN KEY ([ObjectValueId]) REFERENCES [Objects]([Id]),
    CONSTRAINT [FK_Values_ExecutionContexts] FOREIGN KEY ([ObjectValueId]) REFERENCES [Objects]([Id]),
    CONSTRAINT [FK_Values_Metadata] FOREIGN KEY ([MetadataId]) REFERENCES [Metadata]([Id])
);
